### ISSUE TITLE
Collection functions in laravel 9

### ISSUE THREAD

**Issue by abrampl** [nunomaduro/larastan#1137]
- Larastan Version: 9.0
- `--level` used: 5

### Description

```php
$canons->lazy()->each(function (Canon $canon) {
    $canon->state->transitionTo(CanonPendingToBooking::class);
});
```

How to solve this issue ?

Parameter #1 $callback of method Illuminate\Support\LazyCollection<(int|string),mixed>::each() expects callable((int|string), TKey of (int|string)): mixed, Closure(App\Models\Canon): void given.

**Comment by canvural** [comment]
Hi,

I believe this was fixed in Laravel version 9.1 Please upgrade and try again.

Also as of Larastan 2 and LAravel 9, all collection types are moved to Laravel core. So if you have further issues please open an issue there.

**Comment by abrampl** [comment]
I think stilo not working

https://phpstan.org/r/334e6f64-ff6e-4ac1-8558-d1adb1ef4f76

**Comment by abrampl** [comment]
Hi, unfortunetly still not working, same issue i have when i extended default collection for model

```php
class Income extends Model {
    /**
     * @param array<int, Income> $models
     * @return IncomeCollection<Income>
     */
    public function newCollection(array $models = []): IncomeCollection
    {
        return new IncomeCollection($models);
    }
}
```

```php
<?php

namespace Domain\Dossier\Collections;

use Domain\Dossier\Models\Income;
use Illuminate\Database\Eloquent\Collection;

/**
 * @template TModel of Income
 * @extends Collection<int, TModel>
 */
class IncomeCollection extends Collection
{
    public function amount(): float
    {
        return $this->sum(
            fn (Income $income) => $income->json_income->amount()
        );
    }
}
```

PHPStan show error 

 17     Parameter #1 $callback of method Illuminate\Support\Collection<int,TModel of Domain\Dossier\Models\Income>::sum() expects (callable(int): mixed)|string|null, Closure(Domain\Dossier\Models\Income): float|null given.
