### ISSUE TITLE
Two models in MorphTo raises an error

### ISSUE THREAD

**Issue by markuskooche** [nunomaduro/larastan#1223]
Larastan version: 2.1.4

---

It throws an error when using two Models in MorphTo.

```php
/**
 * @return MorphTo<PrivatePost|PublicPost, Picture>
 */
public function post() : MorphTo
{
    return $this->morphTo();
}
```

```
Internal error: Internal error: Call to undefined method PHPStan\Type\UnionType::getClassName() ...
```

**Comment by szepeviktor** [comment]
Hello Markus! 👋 

It may need only a 4 line long PR.

**Comment by canvural** [comment]
Which version are you using? This was fixed in the recent versions.

**Comment by szepeviktor** [comment]
> This was fixed in the recent versions.

Was it #1187?

**Comment by markuskooche** [comment]
I am using version 2.1.4

**Comment by falko100** [comment]
Can confirm this issue still remains on `2.1.4` and `dev-master @ 831f09b`.

```
Method App\Models\Parent::credentials() should return                                                                                          
         Illuminate\Database\Eloquent\Relations\MorphTo<App\Models\ChildX|App\Models\ChildY, App\Models\Parent> but returns  
         Illuminate\Database\Eloquent\Relations\MorphTo<Illuminate\Database\Eloquent\Model, App\Models\Parent>.  
```

**Comment by canvural** [comment]
And I can confirm no one fixed it.

**Comment by canvural** [comment]
This is fixed in the recent versions. Test case: https://github.com/nunomaduro/larastan/blob/340d65ab78e52479c60de27c0851808b1802eaae/tests/Type/data/model-properties-relations.php#L72

**Comment by lcdss** [comment]
> This is fixed in the recent versions. Test case: https://github.com/nunomaduro/larastan/blob/340d65ab78e52479c60de27c0851808b1802eaae/tests/Type/data/model-properties-relations.php#L72

I'm using the latest version of everything and still get this error:

```php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;

final class ChatMessage extends Model
{
    /** @return MorphTo<Lead|User, $this> */
    public function owner(): MorphTo
    {
        return $this->morphTo();
    }
}

```
`Method App\Models\Message::owner() should return Illuminate\Database\Eloquent\Relations\MorphTo<App\Models\Lead|App\Models\User, $this(App\Models\ChatMessage)> but returns Illuminate\Database\Eloquent\Relations\MorphTo<Illuminate\Database\Eloquent\Model, $this(App\Models\ChatMessage)>. PHPStan[return.type](https://phpstan.org/error-identifiers/return.type)`

**Comment by szepeviktor** [comment]
Please open a new issue with complete code samples.
I think it will be resolved quickly.

**Comment by calebdw** [comment]
@lcdss, this is by design---there's no need to open an issue.

`MorphTo` is inherently dynamic and there's no guarantee that only `Lead|User` will be returned. Your solutions are:
1. use `MorphTo<Model, $this>` and handle the models appropriately (`if ($this->owner instanceof User) {...}`)
2. ignore the error

**Comment by lcdss** [comment]
> [@lcdss](https://github.com/lcdss), this is by design---there's no need to open an issue.
> 
> `MorphTo` is inherently dynamic and there's no guarantee that only `Lead|User` will be returned. Your solutions are:
> 
>     1. use `MorphTo<Model, $this>` and handle the models appropriately (`if ($this->owner instanceof User) {...}`)
> 
>     2. ignore the error

Nothing is guaranteed when a type are manually defined in comments, but it doesn't mean the analysis should ignore (I know it's not ignoring - it's just conflicting with Laravel's return definition) what was defined. For now I decided to override Laravel's return definition to stop the annoying error message: 
```php
// Laravel's definition
/** @return \Illuminate\Database\Eloquent\Relations\MorphTo<\Illuminate\Database\Eloquent\Model, $this> */
public function morphTo($name = null, $type = null, $id = null, $ownerKey = null)
{
}
```
```php
/** @return MorphTo<Lead|User, $this> */
public function owner(): MorphTo
{
    /** @var MorphTo<Lead|User, $this> */
    return $this->morphTo();
}
```
I agree that accessing values through the owner relationship should be required to manually narrow the type down, as the same happens with Typescript and most of other languages as well. So no issues there.

**Comment by charlietennant** [comment]
I've ran into a similar version of issue myself today at level 3 (running v3.6.0 of Larastan) where the properties of a related model (via `morphTo`) were erroring per below:

```
Access to an undefined property Illuminate\Database\Eloquent\Model::$id.
         🪪  property.notFound
```

I was able to resolve the error by type-hinting a union type in my class DocBlock for each possible entity:

```php
/**
 * @property RelatedOne|RelatedTwo $exampleable
 */
class Example extends Model
{
    /**
     * XXX
     *
     * @return MorphTo
     */
    public function exampleable(): MorphTo
    {
        return $this->morphTo();
    }  
}
```

**Comment by calebdw** [comment]
@charlietennant you either need to do one of the following:
1. add the models to the relationship generic ( you will need to ignore the return type warning because there's no way for us to know what model is being returned

```php
    /** @return MorphTo<Related1|Related2, $this> */
    public function exampleable(): MorphTo
    {
        return $this->morphTo(); // @phpstan-ignore return.type
    }
```

2. Or you explicitly check / narrow the type everywhere you use the property:

```php
assert($model->example instanceof Related1);
```

**Comment by charlietennant** [comment]
@calebdw thanks. I am satisfied with the solution I posted as it means I don't need to ignore warning nor explicitly check the type everywhere.
