### ISSUE TITLE
Dynamic call to static method truncate()

### ISSUE THREAD

**Issue by spaceemotion** [nunomaduro/larastan#355]
- Larastan Version: 0.4.3
- `--level` used: max

### Description
I'm getting the following:

>  Dynamic call to static method Illuminate\Database\Eloquent\Builder::truncate().

When I use
```php
DB::table('users')->truncate();
```

there's no error.

### Laravel code where the issue was found

```php
Model::query()->truncate();
```

**Comment by canvural** [comment]
I can't reproduce this. I tested with `User::query()->truncate();` in our test cases.

Can you give more information or make a PR with failing test case?

**Comment by spaceemotion** [comment]
Alright, so here's what I have:

**Test.php**
```php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Test extends Model
{

}
```

and the call in a dummy method in a controller:
```php
public function test()
{
    Test::query()->truncate();
}
```

Here's my phpstan.neon.dist:
```neon
includes:
    - vendor/phpstan/phpstan-deprecation-rules/rules.neon
    - vendor/phpstan/phpstan-strict-rules/rules.neon
    - vendor/phpstan/phpstan-mockery/extension.neon
    - vendor/phpstan/phpstan-phpunit/extension.neon
    - vendor/phpstan/phpstan-phpunit/rules.neon
    - vendor/nunomaduro/larastan/extension.neon
parameters:
    level: max
    paths:
        - app
        - config
        - database
        - routes
        - tests
    ignoreErrors:
        - '~UuidInterface~'

        # Ignore this since it would clash with our style rules
        - '~has no typehint specified~'
```

**Comment by canvural** [comment]
The issue is [here](https://github.com/nunomaduro/larastan/blob/master/src/Reflection/EloquentBuilderMethodReflection.php#L68). It's hardcoded to return `true` Since all query builder methods can also be called statically, this was an easy solution. 

So, this needs to be changed, somehow.

**Comment by szepeviktor** [comment]
Model::toBase() may cause this error too.

**Comment by canvural** [comment]
This should be fixed in the latest `dev-master` Can you test again against `dev-master` ?

**Comment by spaceemotion** [comment]
Hm, seems like it still does not work. I've just pasted my Payment examples from #413 into a controller, removed my ignores and ran it against dev-master.

>   64     Dynamic call to static method App\Models\Payment::toBase().
>   70     Dynamic call to static method Illuminate\Database\Eloquent\Model::query().

**Comment by canvural** [comment]
That error message doesn't make sense. There is no dynamic call to the `toBase` or `query`

You mentioned `phpstan/phpstan-strict-rules` caused it before. Is it still the case?

**Comment by spaceemotion** [comment]
If I disable it, it's gone, yes. How would that cause it though? 🤔

**Comment by spaceemotion** [comment]
Just wanted to say that I am still experiencing this with 0.5.2.
