### ISSUE TITLE
Internal error: Class x does not exist

### ISSUE THREAD

**Issue by ForzaSFerrari** [nunomaduro/larastan#77]
just want to make sure. if i get such a message, then something is not laravel compliant, right?
![capture](https://user-images.githubusercontent.com/16107131/43049936-a6076650-8e00-11e8-8e56-4a1ca6e05552.PNG)
that message is completely new.

**Comment by nunomaduro** [comment]
@ForzaSFerrari Hey! That is a internal issue of Larastan or an internal issue of Phpstan.

Please provide my info, context, code, etc.

**Comment by ForzaSFerrari** [comment]
I'm not sure, if this would be the right command for phpstan.
vendor/bin/phpstan analyse --level 0 --debug or vendor/bin/phpstan analyse --level 0 --debug .\path\file.php

WIth path, I got this result
[OK] No errors

Without path, I got this one
```
0 D:\x\vendor\phpstan\phpstan\src\Command\AnalyseCommand.php(239): PHPStan\Command\AnalyseApplication->analyse(Array, Object(PHPStan\Command\ErrorsConsoleStyle), Object(PHPStan\Command\ErrorFormatter\TableErrorFormatter), false, true)
#1 D:\x\vendor\symfony\console\Command\Command.php(251): PHPStan\Command\AnalyseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 D:\x\vendor\symfony\console\Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\x\vendor\symfony\console\Application.php( in D:\x\vendor\phpstan\phpstan\src\Command\AnalyseApplication.php on line 70

Fatal error: Uncaught InvalidArgumentException: At least one path must be specified to analyse. in D:\x\vendor\phpstan\phpstan\src\Command\AnalyseApplication.php:70
Stack trace:
#0 D:\x\vendor\phpstan\phpstan\src\Command\AnalyseCommand.php(239): PHPStan\Command\AnalyseApplication->analyse(Array, Object(PHPStan\Command\ErrorsConsoleStyle), Object(PHPStan\Command\ErrorFormatter\TableErrorFormatter), false, true)
#1 D:\x\vendor\symfony\console\Command\Command.php(251): PHPStan\Command\AnalyseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 D:\x\vendor\symfony\console\Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\x\vendor\symfony\console\Application.php( in D:\x\vendor\phpstan\phpstan\src\Command\AnalyseApplication.php on line 70
```

**Comment by canvural** [comment]
I have the same issue with Larastan 0.2 and PHPStan 0.10.2

In my case it seems to be an issue with Laravel validation.

If I have a code like this:

```php
$validatedData = $request->validate([
    'user_id' => 'required|exists:users,id',
 ]);
```

It gives an error like `Internal error: Class user_id does not exist`

Also same thing happens when I use a from request class. Then try to access the validated data,

```php
$validatedData = $request->validated();

$validatedData['user_id']
```

This also gives `Internal error: Class user_id does not exist`

**Comment by ForzaSFerrari** [comment]
Got another result with another debug command
```
ReflectionException  : Class id does not exist

  at D:\x\vendor\laravel\framework\src\Illuminate\Container\Container.php:767
    763|         if ($concrete instanceof Closure) {
    764|             return $concrete($this, $this->getLastParameterOverride());
    765|         }
    766|
  > 767|         $reflector = new ReflectionClass($concrete);
    768|
    769|         // If the type is not instantiable, the developer is attempting to resolve
    770|         // an abstract type such as an Interface of Abstract Class and there is
    771|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   ReflectionClass::__construct("id")
      D:\x\vendor\laravel\framework\src\Illuminate\Container\Container.php:767

  2   Illuminate\Container\Container::build("id")
      D:\x\vendor\laravel\framework\src\Illuminate\Container\Container.php:646

  Please use the argument -v to see more details.
```

**Comment by szepeviktor** [comment]
Solved in https://github.com/nunomaduro/larastan/commit/84cd60fd17f191a631580ba20f2e76b76c0b3cb7

**Comment by nunomaduro** [comment]
@szepeviktor Not yet. Something is still wrong. Wait a couple of mins.

**Comment by nunomaduro** [comment]
@ForzaSFerrari Thanks for reporting this issue.

Is now fixed on the version `v0.2.2`. Do you mind of performing a quick test?

**Comment by ForzaSFerrari** [comment]
Seems to be fixed @nunomaduro
