### ISSUE TITLE
Model factory is not recognizing correct types when useFactory exists in BaseModel class

### ISSUE THREAD

**Issue by crissi** [nunomaduro/larastan#879]
- Larastan Version: v0.7.2
- `--level` used: 6
- Pull request with failing test:

### Description

Model factory is not recognizing correct types in Laravel v8.50.0, works on v8.44.0

```
Call to an undefined method Illuminate\Database\Eloquent\Collection|Illuminate\Database\Eloquent\Model::pauses()
```

### Laravel code where the issue was found

```php
        $hour = EmpHour::factory()->create([]);

        $hour->pauses()->save($break, ['quantity' => 1]);
```

I tried dev-master for the newest changes and the error still happens.

**Comment by canvural** [comment]
Hi,

Laravel 8 factory change support is currently only in `master` branch. It's not released yet.

If you are trying out the `master` branch you need to put `/** @extends Factory<YourModelHere> */` above your factory class.

**Comment by crissi** [comment]
I tried that. Did not work either:-(

**Comment by szepeviktor** [comment]
Please see https://github.com/nunomaduro/larastan/pull/861

**Comment by crissi** [comment]
Thank you @szepeviktor. 

I looked at that for the @extends info. So quite confident that I am doing the @extends right I will give it another go in the morning to check if I missed/spelled something wrong.

**Comment by canvural** [comment]
For example for `User` model you have `UserFactory`. So in the `database/factories/UserFactory.php` you should have
```php
/** @extends Factory<User> */
class UserFactory extends Factory
{
    ....
}
```

Can you confirm it is like this?

**Comment by erikroznbeker** [comment]
I can't make it work.

- fresh laravel instalation
- composer.json
```
"laravel/framework": "^8.50",
"nunomaduro/larastan": "dev-master"
```
- phpstan.neon
```yaml
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    paths:
        - tests
    level: max
```
- UserFactory.php
```php
/** @extends Factory<User> */
class UserFactory extends Factory
{
```
- ExampleTest.php
```php
<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    public function test_example(): void
    {
        $user = User::factory()->create();
        $userId = $user->id;
        self::assertNotNull($userId);
    }
}
```


```
➜  example-app ./vendor/bin/phpstan analyse
Note: Using configuration file /Users/eroznbeker/www/example-app/phpstan.neon.
 5/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ---------------------------------------------------------------------------------------------------------------- 
  Line   Feature/ExampleTest.php                                                                                         
 ------ ---------------------------------------------------------------------------------------------------------------- 
  13     Access to an undefined property App\Models\User|Illuminate\Database\Eloquent\Collection<App\Models\User>::$id.  
 ------ ---------------------------------------------------------------------------------------------------------------- 

                                                                                                                        
 [ERROR] Found 1 error 
```

I have tried also with
`/** @extends Factory<App\Models\User> */`
and
`/** @extends Factory<\App\Models\User> */`

Can you please instruct me on what else can I do?

**Comment by crissi** [comment]
I can confirm that it does not work either for me

**Comment by canvural** [comment]
@erikroznbeker In your case it works correctly. It determines that the model is `User`. But the issue is we can't determine if it returns single model or a collection. But you'll get this error only on level 7 and higher.

@crissi What is the error you are getting?

**Comment by crissi** [comment]
```
Access to an undefined property                                        
         Illuminate\Database\Eloquent\Collection|Illuminate\Database\Eloquent\  
         Model::$id.                                                            
  109    Call to an undefined method                                            
         Illuminate\Database\Eloquent\Collection|Illuminate\Database\Eloquent\  
         Model::pauses().   
         
```
  
I found out the error. I am using a BaseModel that all my models extend and I only have the **use HasFactory** in the basemodel.


If I move the **use HasFactory** to the model in question it works

**Comment by crissi** [comment]
Should I close this as won't fix? or is this something we should find a solution for?

**Comment by szepeviktor** [comment]
> we can't determine if it returns single model or a collection

This is the problem.
I see it as a limitation of static analysis.

**Comment by canvural** [comment]
> Should I close this as won't fix? or is this something we should find a solution for?

Are you talking about the `use HasFactory` in parent model? I can take a look into it later.

**Comment by crissi** [comment]
> > Should I close this as won't fix? or is this something we should find a solution for?
> 
> Are you talking about the `use HasFactory` in parent model? I can take a look into it later.

yes, awesome

**Comment by erikroznbeker** [comment]
> @erikroznbeker In your case it works correctly. It determines that the model is `User`. But the issue is we can't determine if it returns single model or a collection. But you'll get this error only on level 7 and higher.

You are right. Thank you.

**Comment by crissi** [comment]
can see laravel have a helper: **trait_uses_recursive** We could use that to check if hat HasFactory trait?

**Comment by crissi** [comment]
I can make a pr tomorrow, if you are not on it @canvural !?

**Comment by canvural** [comment]
@crissi We don't check if a model has `HasFactory` trait or not. So I don't think that's the solution. I'll try to take a look at it later.

**Comment by canvural** [comment]
@crissi Should be fixed with https://github.com/nunomaduro/larastan/commit/6a03ad7899f5b71133c459df0260e19491dc5ed4 Can you check again?

**Comment by crissi** [comment]
works like a charm, good job 👍

**Comment by greimers** [comment]
For anybody who still get errors and lands here:

It took me several hours to figure out that PHPStan caches the results of analysis runs. To fix the issues with the factories, you need to add the `@extends` doc comment as described above. However, this change does not clear the PHPStan cache, so you will still get errors. 
**You should run `vendor/bin/phpstan clear-result-cache` to make sure you don't see cached errors that are actually solved by changed in the comments.**
